@startuml
class com.froztlass.tafsirmate.SplashFragment {
- FragmentSplashBinding? _binding
-  binding
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
- Boolean onBoardingFinished()
+ void onDestroyView()
}


class com.froztlass.tafsirmate.ExampleUnitTest {
+ void addition_isCorrect()
}

class com.froztlass.tafsirmate.onboarding.screens.ThirdScreen {
- FragmentThirdScreenBinding? _binding
-  binding
- GoogleSignInClient googleSignInClient
- FirebaseAuth auth
-  googleSignInLauncher
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
- void signInWithGoogle()
- void firebaseAuthWithGoogle(String)
- void saveUserToFirestore(FirebaseUser)
+ void onDestroyView()
}


class com.froztlass.tafsirmate.databinding.FragmentViewPagerBinding {
- ConstraintLayout rootView
+ ViewPager2 viewPager
+ ConstraintLayout getRoot()
+ {static} FragmentViewPagerBinding inflate(LayoutInflater)
+ {static} FragmentViewPagerBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentViewPagerBinding bind(View)
}


class com.froztlass.tafsirmate.onboarding.screens.FirstScreen {
+ View? onCreateView(LayoutInflater,ViewGroup?,Bundle?)
}

class com.froztlass.tafsirmate.MenuFragment {
- FragmentMenuBinding? _binding
-  binding
-  homeFragment
-  botFragment
-  profileFragment
- Fragment activeFragment
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
- void setupBottomNavigation()
- void showFragment(Fragment)
+ void onDestroyView()
}


class com.froztlass.tafsirmate.api.EquranRepository {
- EquranApiService api
+ void getSuratList((List<Surat>?) -> Unit)
+ void getSurahDetail(Int,(Surat?) -> Unit)
}


class com.froztlass.tafsirmate.databinding.ActivityMainBinding {
- ConstraintLayout rootView
+ FragmentContainerView fragmentContainerView5
+ ConstraintLayout getRoot()
+ {static} ActivityMainBinding inflate(LayoutInflater)
+ {static} ActivityMainBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ActivityMainBinding bind(View)
}


class com.froztlass.tafsirmate.model.BotViewModel$Companion {
-  CHAT_HISTORY_KEY
}

class com.froztlass.tafsirmate.model.BotViewModel {
+ MutableList<Pair<String, Boolean>> chatHistory
+ void addMessage(String,Boolean)
}


class com.froztlass.tafsirmate.databinding.FragmentBotBinding {
- LinearLayout rootView
+ LinearLayout chatLayout
+ LinearLayout inputContainer
+ EditText inputText
+ ImageButton micButton
+ ScrollView scrollView
+ ImageButton sendButton
+ TextView tvGreetingUser
+ TextView tvWelcomeMessage
+ LinearLayout getRoot()
+ {static} FragmentBotBinding inflate(LayoutInflater)
+ {static} FragmentBotBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentBotBinding bind(View)
}


class com.froztlass.tafsirmate.databinding.FragmentHomeBinding {
- FrameLayout rootView
+ ImageView btnBackArrow
+ ImageButton btnFilter
+ ImageView ivUserProfile
+ RecyclerView recyclerViewAyat
+ RecyclerView recyclerViewSurat
+ CardView searchContainer
+ SearchView searchView
+ TextView tvGreetingUser
+ TextView tvSurahName
+ TextView tvWelcomeMessage
+ FrameLayout getRoot()
+ {static} FragmentHomeBinding inflate(LayoutInflater)
+ {static} FragmentHomeBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentHomeBinding bind(View)
}


class com.froztlass.tafsirmate.model.Surat {
}
class com.froztlass.tafsirmate.model.Ayat {
}
class com.froztlass.tafsirmate.databinding.CustomDialogBinding {
- LinearLayout rootView
+ TextView dialogTextView
+ ImageView logoImageView
+ TextView versionTextView
+ LinearLayout getRoot()
+ {static} CustomDialogBinding inflate(LayoutInflater)
+ {static} CustomDialogBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} CustomDialogBinding bind(View)
}


class com.froztlass.tafsirmate.HomeViewModel {
-  _suratList
+ LiveData<List<Surat>> suratList
-  _ayatList
+ LiveData<List<Ayat>> ayatList
+ void loadSuratList()
+ void loadAyatList(Int)
}


class com.froztlass.tafsirmate.DetailFragment {
- Int? surahNumber
- String? surahName
- FragmentDetailBinding binding
- AyatAdapter ayatAdapter
+ void onCreateView(void,LayoutInflater,ViewGroup?,void,Bundle?)
+ void null()
+ void onViewCreated(View,Bundle?)
- void loadSurahDetail()
}


class com.froztlass.tafsirmate.HomeFragment {
- FragmentHomeBinding? _binding
-  binding
- SuratAdapter suratAdapter
- HomeViewModel homeViewModel
- AyatAdapter ayatAdapter
- List<Surat> allSuratList
-  doubleBackToExitPressedOnce
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
- void showSurahDetails(Surat)
- void filterSurat(String?)
- void filterSurat2(String?)
+ void onDestroyView()
}


class com.froztlass.tafsirmate.onboarding.screens.SecondScreen {
+ View? onCreateView(LayoutInflater,ViewGroup?,Bundle?)
}

class com.froztlass.tafsirmate.databinding.FragmentDetailBinding {
- LinearLayout rootView
+ RecyclerView recyclerViewAyat
+ TextView tvSurahName
+ TextView tvSurahNumber
+ LinearLayout getRoot()
+ {static} FragmentDetailBinding inflate(LayoutInflater)
+ {static} FragmentDetailBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentDetailBinding bind(View)
}


class com.froztlass.tafsirmate.adapter.SuratAdapter {
}
class com.froztlass.tafsirmate.adapter.SuratViewHolder {
}
class com.froztlass.tafsirmate.databinding.ItemAyatBinding {
- CardView rootView
+ ImageButton btnAI
+ Button btnSpeak
+ TextView tvAiResponse
+ TextView tvAyatLatin
+ TextView tvAyatNumber
+ TextView tvAyatTerjemahan
+ TextView tvAyatText
+ CardView getRoot()
+ {static} ItemAyatBinding inflate(LayoutInflater)
+ {static} ItemAyatBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ItemAyatBinding bind(View)
}


class com.froztlass.tafsirmate.model.SurahResponse {
}
class com.froztlass.tafsirmate.databinding.FragmentMenuBinding {
- ConstraintLayout rootView
+ BottomNavigationView bottomNavigation
+ FrameLayout frameContainer
+ ConstraintLayout getRoot()
+ {static} FragmentMenuBinding inflate(LayoutInflater)
+ {static} FragmentMenuBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentMenuBinding bind(View)
}


class com.froztlass.tafsirmate.model.ApiResponse {
}
interface com.froztlass.tafsirmate.api.EquranApiService {
+ Call<SurahResponse> getSuratList()
+ Call<ApiResponse> getSurah(Int)
}

class com.froztlass.tafsirmate.databinding.FragmentFirstScreenBinding {
- ConstraintLayout rootView
+ ImageView ivBtn
+ ImageView ivBtnR1
+ ImageView ivRectangle
+ LottieAnimationView lottieAnimationView
+ TextView next
+ TextView tvGreetings1
+ TextView tvGreetings2
+ TextView tvGreetings3
+ ConstraintLayout getRoot()
+ {static} FragmentFirstScreenBinding inflate(LayoutInflater)
+ {static} FragmentFirstScreenBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentFirstScreenBinding bind(View)
}


class com.froztlass.tafsirmate.databinding.FragmentThirdScreenBinding {
- ConstraintLayout rootView_
+ SignInButton googleSignInButton
+ ImageView ivRectangle3
+ LottieAnimationView lottieAnimationView
+ ConstraintLayout rootView
+ TextView tvGreetings13
+ TextView tvGreetings23
+ TextView tvGreetings33
+ ConstraintLayout getRoot()
+ {static} FragmentThirdScreenBinding inflate(LayoutInflater)
+ {static} FragmentThirdScreenBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentThirdScreenBinding bind(View)
}


class com.froztlass.tafsirmate.databinding.FragmentSecondScreenBinding {
- ConstraintLayout rootView
+ ImageView ivBtn2
+ ImageView ivBtnR2
+ ImageView ivRectangle2
+ LottieAnimationView lottieAnimationView
+ TextView next2
+ TextView tvGreetings12
+ TextView tvGreetings22
+ TextView tvGreetings32
+ ConstraintLayout getRoot()
+ {static} FragmentSecondScreenBinding inflate(LayoutInflater)
+ {static} FragmentSecondScreenBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentSecondScreenBinding bind(View)
}


class com.froztlass.tafsirmate.ExampleInstrumentedTest {
+ void useAppContext()
}

class com.froztlass.tafsirmate.MainActivity {
+ void onCreate(Bundle?)
- String performHeavyOperation()
- void updateUI(String)
- void setStatusBarIconColor(Boolean)
- Boolean isLightBackground(Int)
}

class com.froztlass.tafsirmate.databinding.FragmentSplashBinding {
- ConstraintLayout rootView
+ LottieAnimationView ivLogo
+ TextView tvAppName
+ TextView tvAppName2
+ ConstraintLayout getRoot()
+ {static} FragmentSplashBinding inflate(LayoutInflater)
+ {static} FragmentSplashBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentSplashBinding bind(View)
}


class com.froztlass.tafsirmate.onboarding.ViewPagerAdapter {
}
class com.froztlass.tafsirmate.ProfileFragment {
- FragmentProfileBinding? _binding
-  binding
- FirebaseAuth auth
- GoogleSignInClient googleSignInClient
- SharedPreferences sharedPref
+ View onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
+ void onDestroyView()
}


class com.froztlass.tafsirmate.adapter.AyatAdapter$AyatViewHolder {
}
class com.froztlass.tafsirmate.adapter.AyatAdapter {
-  ayatList
+ void submitList(List<Ayat>)
+ AyatViewHolder onCreateViewHolder(ViewGroup,Int)
+ void onBindViewHolder(AyatViewHolder,Int)
+ Int getItemCount()
+ void null()
}


class com.froztlass.tafsirmate.databinding.FragmentProfileBinding {
- ConstraintLayout rootView
+ Button logoutButton
+ TextView nameTextView
+ ImageView profileImageView
+ ConstraintLayout getRoot()
+ {static} FragmentProfileBinding inflate(LayoutInflater)
+ {static} FragmentProfileBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} FragmentProfileBinding bind(View)
}


class com.froztlass.tafsirmate.onboarding.ViewPagerFragment {
+ View? onCreateView(LayoutInflater,ViewGroup?,Bundle?)
+ void onViewCreated(View,Bundle?)
}

class com.froztlass.tafsirmate.BotFragment {
-  client
-  apiKey
- LinearLayout chatLayout
- ScrollView scrollView
- EditText inputText
- ImageButton sendButton
- ImageButton micButton
- LinearLayout inputContainer
- TextView greetingText
- TextView welcomeMessage
- SpeechRecognizer speechRecognizer
- TextToSpeech textToSpeech
- BotViewModel viewModel
-  messageHistory
-  isUserScrolling
-  isVoiceInput
+ void onCreateView(void,LayoutInflater,ViewGroup?,void,Bundle?)
+ void null()
+ void onInit(Int)
- void setGreetingMessage()
- String getGreetingMessage()
- void restoreChatHistory()
- void adjustInputPosition(View)
- void addMessageBubble(String,Boolean)
- void sendMessageToOpenAI(String,Boolean)
- void startSpeechRecognition()
- void speakText(String)
- String removeMarkdown(String)
- String getTafsirAlFatihahFromJson()
}


class com.froztlass.tafsirmate.databinding.ItemSuratBinding {
- CardView rootView
+ TextView suratName
+ TextView tvSuratArti
+ TextView tvSuratJumlahAyat
+ CardView getRoot()
+ {static} ItemSuratBinding inflate(LayoutInflater)
+ {static} ItemSuratBinding inflate(LayoutInflater,ViewGroup,boolean)
+ {static} ItemSuratBinding bind(View)
}




androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.SplashFragment
androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.onboarding.screens.ThirdScreen
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentViewPagerBinding
androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.onboarding.screens.FirstScreen
androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.MenuFragment
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.ActivityMainBinding
com.froztlass.tafsirmate.model.BotViewModel +.. com.froztlass.tafsirmate.model.BotViewModel$Companion
androidx.lifecycle.ViewModel <|-- com.froztlass.tafsirmate.model.BotViewModel
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentBotBinding
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentHomeBinding
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.CustomDialogBinding
androidx.lifecycle.ViewModel <|-- com.froztlass.tafsirmate.HomeViewModel
androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.DetailFragment
androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.HomeFragment
androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.onboarding.screens.SecondScreen
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentDetailBinding




androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.ItemAyatBinding
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentMenuBinding
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentFirstScreenBinding
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentThirdScreenBinding
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentSecondScreenBinding
androidx.appcompat.app.AppCompatActivity <|-- com.froztlass.tafsirmate.MainActivity
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentSplashBinding
androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.ProfileFragment
com.froztlass.tafsirmate.adapter.AyatAdapter +.. com.froztlass.tafsirmate.adapter.AyatAdapter$AyatViewHolder
com.froztlass.tafsirmate.adapter.ViewHolder <|-- com.froztlass.tafsirmate.adapter.AyatAdapter$AyatViewHolder


com.froztlass.tafsirmate.adapter.Adapter <|-- com.froztlass.tafsirmate.adapter.AyatAdapter
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.FragmentProfileBinding
androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.onboarding.ViewPagerFragment
androidx.fragment.app.Fragment <|-- com.froztlass.tafsirmate.BotFragment
com.froztlass.tafsirmate.OnInitListener <|.. com.froztlass.tafsirmate.BotFragment
androidx.viewbinding.ViewBinding <|.. com.froztlass.tafsirmate.databinding.ItemSuratBinding
@enduml