@startuml

skinparam classAttributeIconSize 0
skinparam classFontSize 12
skinparam defaultTextAlignment center
hide circle

'=========================
' ABSTRACT CLASS & INTERFACE
'=========================
interface androidx.viewbinding.ViewBinding
interface androidx.fragment.app.Fragment
interface androidx.appcompat.app.AppCompatActivity
interface androidx.lifecycle.ViewModel
interface com.froztlass.tafsirmate.OnInitListener

'=========================
' ACTIVITY
'=========================
class com.froztlass.tafsirmate.MainActivity {
  - requestAudioPermission
  + void onCreate(Bundle?)
  - String performHeavyOperation()
  - void updateUI(String)
  - void setStatusBarIconColor(Boolean)
  - Boolean isLightBackground(Int)
  - void showPermissionDeniedDialog()
  - void openAppSettings()
}
com.froztlass.tafsirmate.MainActivity --|> androidx.appcompat.app.AppCompatActivity

'=========================
' API
'=========================
interface com.froztlass.tafsirmate.api.EquranApiService {
  + Call<SurahResponse> getSuratList()
  + Call<ApiResponse> getSurah(Int)
}

class com.froztlass.tafsirmate.api.EquranRepository {
  - EquranApiService api
  + void getSuratList((List<Surat>?) -> Unit)
  + void getSurahDetail(Int, (Surat?) -> Unit)
}

'=========================
' MODEL
'=========================
class com.froztlass.tafsirmate.model.ApiResponse
class com.froztlass.tafsirmate.model.Surat
class com.froztlass.tafsirmate.model.Ayat
class com.froztlass.tafsirmate.model.ChatItem
class com.froztlass.tafsirmate.model.SurahResponse
class com.froztlass.tafsirmate.model.BotViewModel {
  + MutableList<Pair<String, Boolean>> chatHistory
  + void addMessage(String, Boolean)
}
class com.froztlass.tafsirmate.model.BotViewModel$Companion

com.froztlass.tafsirmate.model.BotViewModel --> com.froztlass.tafsirmate.model.BotViewModel$Companion
com.froztlass.tafsirmate.model.BotViewModel --|> androidx.lifecycle.ViewModel

'=========================
' ADAPTER
'=========================
class com.froztlass.tafsirmate.adapter.AyatAdapter {
  + void submitData(Surat)
  + Int getItemCount()
  + Int getItemViewType(Int)
  + RecyclerView.ViewHolder onCreateViewHolder(ViewGroup, Int)
  + void onBindViewHolder(RecyclerView.ViewHolder, Int)
}
class com.froztlass.tafsirmate.adapter.AyatAdapter$Companion
class com.froztlass.tafsirmate.adapter.AyatAdapter$HeaderViewHolder
class com.froztlass.tafsirmate.adapter.AyatAdapter$AyatViewHolder
class com.froztlass.tafsirmate.adapter.ChatAdapter
class com.froztlass.tafsirmate.adapter.ChatViewHolder
class com.froztlass.tafsirmate.adapter.SuratAdapter
class com.froztlass.tafsirmate.adapter.SuratViewHolder

com.froztlass.tafsirmate.adapter.AyatAdapter --> com.froztlass.tafsirmate.adapter.AyatAdapter$Companion
com.froztlass.tafsirmate.adapter.AyatAdapter --> com.froztlass.tafsirmate.adapter.AyatAdapter$HeaderViewHolder
com.froztlass.tafsirmate.adapter.AyatAdapter --> com.froztlass.tafsirmate.adapter.AyatAdapter$AyatViewHolder

'=========================
' VIEWMODEL
'=========================
class com.froztlass.tafsirmate.HomeViewModel {
  + LiveData<List<Surat>> suratList
  + LiveData<List<Ayat>> ayatList
  + void loadSuratList()
  + void loadAyatList(Int)
}
com.froztlass.tafsirmate.HomeViewModel --|> androidx.lifecycle.ViewModel

'=========================
' FRAGMENT
'=========================
class com.froztlass.tafsirmate.SplashFragment
class com.froztlass.tafsirmate.HomeFragment
class com.froztlass.tafsirmate.MenuFragment
class com.froztlass.tafsirmate.ProfileFragment
class com.froztlass.tafsirmate.ChatHistoryFragment
class com.froztlass.tafsirmate.DetailFragment
class com.froztlass.tafsirmate.BotFragment
class com.froztlass.tafsirmate.onboarding.ViewPagerFragment
class com.froztlass.tafsirmate.onboarding.ViewPagerAdapter
class com.froztlass.tafsirmate.onboarding.screens.FirstScreen
class com.froztlass.tafsirmate.onboarding.screens.SecondScreen
class com.froztlass.tafsirmate.onboarding.screens.ThirdScreen

com.froztlass.tafsirmate.SplashFragment --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.HomeFragment --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.MenuFragment --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.ProfileFragment --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.ChatHistoryFragment --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.DetailFragment --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.BotFragment --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.onboarding.ViewPagerFragment --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.onboarding.screens.FirstScreen --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.onboarding.screens.SecondScreen --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.onboarding.screens.ThirdScreen --|> androidx.fragment.app.Fragment
com.froztlass.tafsirmate.onboarding.screens.ThirdScreen ..|> com.froztlass.tafsirmate.OnInitListener

'=========================
' VIEWBINDING
'=========================
package databinding {
  class FragmentHomeBinding
  class FragmentChatHistoryBinding
  class FragmentDetailBinding
  class FragmentProfileBinding
  class FragmentMenuBinding
  class FragmentBotBinding
  class FragmentFirstScreenBinding
  class FragmentSecondScreenBinding
  class FragmentThirdScreenBinding
  class FragmentSplashBinding
  class FragmentViewPagerBinding
  class ItemSuratBinding
  class ItemSuratHeaderBinding
  class ItemAyatBinding
  class ItemChatAiBinding
  class ItemChatBinding
  class ItemChatUserBinding
  class ItemChatHistoryBinding
  class ActivityMainBinding

  FragmentHomeBinding --|> androidx.viewbinding.ViewBinding
  FragmentChatHistoryBinding --|> androidx.viewbinding.ViewBinding
  FragmentDetailBinding --|> androidx.viewbinding.ViewBinding
  FragmentProfileBinding --|> androidx.viewbinding.ViewBinding
  FragmentMenuBinding --|> androidx.viewbinding.ViewBinding
  FragmentBotBinding --|> androidx.viewbinding.ViewBinding
  FragmentFirstScreenBinding --|> androidx.viewbinding.ViewBinding
  FragmentSecondScreenBinding --|> androidx.viewbinding.ViewBinding
  FragmentThirdScreenBinding --|> androidx.viewbinding.ViewBinding
  FragmentSplashBinding --|> androidx.viewbinding.ViewBinding
  FragmentViewPagerBinding --|> androidx.viewbinding.ViewBinding
  ItemSuratBinding --|> androidx.viewbinding.ViewBinding
  ItemSuratHeaderBinding --|> androidx.viewbinding.ViewBinding
  ItemAyatBinding --|> androidx.viewbinding.ViewBinding
  ItemChatAiBinding --|> androidx.viewbinding.ViewBinding
  ItemChatBinding --|> androidx.viewbinding.ViewBinding
  ItemChatUserBinding --|> androidx.viewbinding.ViewBinding
  ItemChatHistoryBinding --|> androidx.viewbinding.ViewBinding
  ActivityMainBinding --|> androidx.viewbinding.ViewBinding
}

@enduml
